/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { CampaignMatchPOSTBodyFacetsItem } from "./campaignMatchPOSTBodyFacetsItem";
import type { CampaignMatchPOSTBodyQueriesItem } from "./campaignMatchPOSTBodyQueriesItem";

export type CampaignMatchPOSTBody = {
  /** A facet to match against */
  facets?: CampaignMatchPOSTBodyFacetsItem[];
  /** The users free-text queries, used in a fuzzy-search. */
  queries?: CampaignMatchPOSTBodyQueriesItem[];
};
