/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { CampaignMatchPOSTBodyItemValuesItem } from "./campaignMatchPOSTBodyItemValuesItem";

export type CampaignMatchPOSTBodyItem = {
  name?: string;
  values?: CampaignMatchPOSTBodyItemValuesItem[];
};
