/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type CampaignMatchPOSTBodyItemValuesItem = {
  key?: string;
  term?: string;
  score?: number;
};
