/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provided by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type DplOpeningHoursUpdatePATCH_Format =
  (typeof DplOpeningHoursUpdatePATCH_Format)[keyof typeof DplOpeningHoursUpdatePATCH_Format];

export const DplOpeningHoursUpdatePATCH_Format = {
  json: "json"
} as const;
