<?php

/**
 * @file
 * DPL Biblio module.
 *
 * Handles configuration for the Biblio adapter which is set to replace
 * Publizon as the service for digital materials. The adapter is rolled out
 * behind a feature flag so Publizon remains the default until a library
 * explicitly enables the Biblio adapter.
 */

use Drupal\Core\Cache\CacheableMetadata;

/**
 * Implements hook_dpl_react_apps_api_urls().
 *
 * @return array<string, string>
 *   Service to URL mapping.
 */
function dpl_biblio_dpl_react_apps_api_urls(): array {
  /** @var \Drupal\dpl_biblio\DplBiblioSettings $biblio_settings */
  $biblio_settings = \Drupal::service('dpl_biblio.settings');

  if (!$base_url = $biblio_settings->getBaseUrl()) {
    return [];
  }

  return [
    'biblio' => $base_url,
  ];
}

/**
 * Implements hook_dpl_react_apps_data().
 *
 * Expose the Biblio adapter feature flag to all React apps as
 * data-use-biblio-adapter-config.
 *
 * @param mixed[] $data
 *   The data to provide to the React apps.
 * @param mixed[] $variables
 *   The variables for the theme hook.
 */
function dpl_biblio_dpl_react_apps_data(array &$data, array &$variables): void {
  /** @var \Drupal\dpl_biblio\DplBiblioSettings $biblio_settings */
  $biblio_settings = \Drupal::service('dpl_biblio.settings');

  // Make sure that changed settings are invalidating the cache.
  $cache_metadata = CacheableMetadata::createFromRenderArray($variables);
  $cache_metadata->addCacheableDependency($biblio_settings);
  $cache_metadata->applyTo($variables);

  $data['configs'] += [
    'use-biblio-adapter' => $biblio_settings->isEnabled() ? '1' : '0',
  ];
}
