/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Collection List
 * OpenAPI spec version: 2.0.0
 */

export type VersionParameter =
  (typeof VersionParameter)[keyof typeof VersionParameter];

export const VersionParameter = {
  NUMBER_2: 2
} as const;
