/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { CreateReservation } from "./createReservation";

export interface CreateReservationBatch {
  /** Reservations with duplicate record id's will be removed. */
  reservations: CreateReservation[];
}
