/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface FavoriteV1 {
  bibliographicRecordId: string;
  periodicalNumber?: string;
  periodicalVolume?: string;
  periodicalYear?: string;
}
