/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface PeriodicalInformation {
  number?: string;
  volume?: string;
  year?: string;
}
