/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { AgencyDepartment } from "./agencyDepartment";
import type { AgencyLocation } from "./agencyLocation";
import type { AgencySection } from "./agencySection";
import type { AgencySublocation } from "./agencySublocation";

export interface PlacementV1 {
  /** Placement department */
  department?: AgencyDepartment;
  /** Placement location */
  location?: AgencyLocation;
  /** Placement section */
  section?: AgencySection;
  /** Placement sublocation */
  sublocation?: AgencySublocation;
}
