<?php

use Drupal\bnf\BnfStateEnum;
use Drupal\bnf_client\Services\BnfExporter;
use Drupal\Core\Form\FormStateInterface;
use Drupal\drupal_typed\DrupalTyped;

/**
 * A custom form submit handler, that publishes node, and "exports" to BNF.
 *
 * This should be moved to FormHooks when upgrading to Drupal 11.3.
 */
function bnf_client_form_node_form_submit(array $form, FormStateInterface $form_state): void {
  /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
  $form_object = $form_state->getFormObject();

  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_object->getEntity();

  $bnf_keep_updated = $form_state->getValue('bnf_keep_updated');

  // If the content has been imported, the editor can choose if they want to
  // keep it up-to-date with the BNF server.
  // See more info in BnfStateEnum.
  if (!is_null($bnf_keep_updated)) {
    $state = ($bnf_keep_updated) ? BnfStateEnum::Imported : BnfStateEnum::LocallyClaimed;
    $node->set(BnfStateEnum::FIELD_NAME, $state);
    $node->save();
  }

  if (empty($form_state->getValue('bnf_export'))) {
    return;
  }

  try {
    $node->setPublished();
    $node->save();
  }
  catch (\Exception $e) {
    \Drupal::logger('bnf_client')->error('Could not publish node as part of BNF export. @message', ['@message' => $e->getMessage()]);

    \Drupal::messenger()->addError(
      t("Could not publish node - will not send to BNF.", [], ['context' => 'BNF'])
    );
  }

  try {
    $service = DrupalTyped::service(BnfExporter::class, 'bnf_client.exporter');
    $service->exportNode($node);

    \Drupal::messenger()->addStatus(
      t("Content has been published and sent to BNF.", [], ['context' => 'BNF'])
    );
  }
  catch (\Throwable $e) {
    \Drupal::messenger()->addError(t('Could not export node to BNF.', [], ['context' => 'BNF']));

    \Drupal::logger('bnf_client')->error('Could not export node to BNF. @message', ['@message' => $e->getMessage()]);

  }
}
