query getDplCmsPrivateConfiguration {
  goConfiguration {
    private {
      unilogin {
        pubHubRetailerKeyCode
      }
    }
  }
}

query getDplCmsPublicConfiguration {
  goConfiguration {
    public {
      libraryInfo {
        name
      }
      loginUrls {
        adgangsplatformen
        unilogin
      }
      logoutUrls {
        adgangsplatformen
      }
      mapp {
        domain
        id
      }
      unilogin {
        municipalityId
      }
      blacklistedAvailabilityBranches
      biblio {
        enabled
        baseUrl
        sdk {
          applicationId
          firebaseApiKey
          firebaseProjectId
          firebaseAppId
          readerApiKey
        }
      }
      smsNotificationsEnabled
    }
  }
}
