services:
  node:
    image: node:24.15
    init: true
    working_dir: /app/design-system
    volumes:
      - ../:/app
    user: ${UID:-1000}:${GID:-1000}
    environment:
      HOME: /tmp
      COREPACK_HOME: /tmp/corepack
      PNPM_HOME: /tmp/pnpm
      PATH: /tmp/pnpm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      VIRTUAL_HOST: ${COMPOSE_PROJECT_NAME}.local
      VIRTUAL_PORT: 6006
      STORYBOOK_CLIENT_ID: bdc1d425-9117-4867-acb9-c7307ddc2e0f

volumes:
  projectroot:
    driver_opts:
      type: none
      device: $PWD
      o: bind
