name: Go / E2E tests

on:
  pull_request:
    paths:
      - "go/**"
      - "packages/**"
      - ".github/workflows/go-*.yml"

jobs:
  check:
    name: Go / E2E job with Cypress
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: go

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Required to retrieve git history

      - uses: ./.github/actions/common-setup-js
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Load environment variables
        uses: cardinalby/export-env-action@v2
        with:
          envFile: "go/.env.test"

      - name: Build the Nextjs app and run Cypress tests
        uses: cypress-io/github-action@v7
        env:
          # A bug in the current version of Nextjs causes NODE_ENV=test to brick the build
          # By overridding the variables here we can ensure that the correct urls are set
          TEST_MODE: true
          DPL_CMS_BASE_URL: http://localhost:9000
          UNILOGIN_CLIENT_ID: http://localhost:9000/client
          UNILOGIN_WELLKNOWN_URL: http://localhost:9000
          DPL_GO_BASE_URL: http://localhost:3000

        with:
          install: false
          build: pnpm run build
          start: pnpm run start
          command: pnpm run cypress:run
          browser: chrome
          working-directory: go
