name: Go / ESLint check

on:
  pull_request:
    paths:
      - 'go/**'
      - '.github/workflows/go-*.yml'
      - pnpm-lock.yaml
      - pnpm-workspace.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/common-setup-js
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run linter
        run: pnpm run lint
        working-directory: go
