name: Go / Prettier check

on:
  pull_request:
    paths:
      - 'go/**'
      - '.github/workflows/go-*.yml'
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: go

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - uses: ./.github/actions/common-setup-js
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Prettier formatting
        run: pnpm run format:check
