# Workflow name
name: "Go / Unit test"

# Event for the workflow
on:
  pull_request:
    paths:
      - 'go/**'
      - '.github/workflows/go-*.yml'

# List of jobs
jobs:
  unit:
    name: Unit test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: go

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - uses: actions/setup-node@v6
        with:
          node-version-file: "go/.nvmrc"

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Run unit tests
        run: npm run test:unit:once
