---
name: React / Codegen

on:
  pull_request:
    paths:
      - 'react/**'
      - 'schemas/openapi/**'
      - 'schemas/graphql/dbc-fbi.temp-next.graphql'
      - 'cms/openapi.json'
      - '.github/workflows/react-codegen.yml'

concurrency:
  group: ${{ github.repository_id }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codegen:
    name: Generated clients
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/common-setup-js
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install go-task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Codegen - DBC gateway GraphQL
        run: task codegen:dbc:gateway
        working-directory: react

      - name: Codegen - REST services
        run: task codegen:rest-services
        working-directory: react

      - name: Codegen - FBS client
        run: task codegen:client:fbs
        working-directory: react

      - name: Codegen - Publizon client
        run: task codegen:client:publizon
        working-directory: react

      - name: Codegen - dpl-cms client
        run: task codegen:client:dpl-cms
        working-directory: react

      - name: Ensure generated client code has not drifted
        run: git diff --exit-code
