---
name: React / Codegen

on:
  pull_request:
    paths:
      - 'react/**'
      - 'cms/openapi.json'
      - '.github/workflows/react-codegen-check.yml'

jobs:
  codegen-dpl-cms:
    name: Generated clients
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: 'react/.nvmrc'
          cache: 'yarn'
          cache-dependency-path: 'react/yarn.lock'
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Generate FBS client code
        run: npm run codegen:client:fbs

      - name: Generate Publizon client code
        run: npm run codegen:client:publizon

      - name: Generate DPL CMS client code
        run: npm run codegen:client:dpl-cms

      - name: Generate DBC Gateway GraphQL client code
        env:
          STORYBOOK_LIBRARY_TOKEN: ${{ secrets.STORYBOOK_LIBRARY_TOKEN }}
        run: npm run codegen:dbc:gateway

      - name: Ensure generated client code has not drifted
        run: git diff --exit-code
