# Workflow name
name: "Service Layer / FBS / Unit test"

# Event for the workflow
on:
  pull_request:
    paths:
      - 'packages/js/service-layer/fbs/**'
      - '.github/workflows/service-layer-fbs-*.yml'

# List of jobs
jobs:
  unit:
    name: Unit test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/js/service-layer/fbs

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version-file: "packages/js/service-layer/fbs/.nvmrc"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn test
